name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Setup Gradle with the latest version
    - name: Setup Gradle
      uses: eskatos/gradle-setup-action@v1 # Burada eylemin gerçek deposunu belirttik.
      with:
        gradle-version: '8.7' # or whatever version you prefer

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph
    - name: Generate and submit dependency graph
      uses: gradle/dependency-submission@v3
